FinanzasWeb/Models/Cuenta.cs
namespace FinanzasWeb.Models;

public class Cuenta
{
    public int Id { get; set; }
    public string Nombre { get; set; }
    public string Categoria { get; set; }
    public int TipoId { get; set; }
    public decimal SaldoInicial { get; set; }
    public string Moneda { get; set; }
    public TipoCuenta? TipoCuenta {get; set; }
    
    
}

FinanzasWeb/Models/ErrorViewModel.cs
namespace FinanzasWeb.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

FinanzasWeb/Models/TipoCuenta.cs
namespace FinanzasWeb.Models;

public class TipoCuenta
{
    public int Id { get; set; }
    public string Nombre { get; set; }
    public bool EsCredito { get; set; }
}

FinanzasWeb/Models/Transaccion.cs
namespace FinanzasWeb.Models;

public class Transaccion
{
    public int Id { get; set; }
    public string Tipo { get; set; }
    public int CuentaId { get; set; } 
    public DateTime Fecha { get; set; }
    public string Descripcion { get; set; }
    public decimal Monto { get; set; }
   
    
}

FinanzasWeb/Controllers/CuentaController.cs
using FinanzasWeb.DB;
using FinanzasWeb.Models;
using FinanzasWeb.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace FinanzasWeb.Controllers;

public class CuentaController : Controller
{
    private readonly ITipoCuentaRepositorio _tipoCuentaRepositorio;
    private readonly ICuentaRepositorio _cuentaRepositorio;
    private DbEntities _dbEntities;

    public CuentaController(ITipoCuentaRepositorio tipoCuentaRepositorio, ICuentaRepositorio cuentaRepositorio,
        DbEntities dbEntities)
    {
        _tipoCuentaRepositorio = tipoCuentaRepositorio;
        _cuentaRepositorio = cuentaRepositorio;
        _dbEntities = dbEntities;


    }

    [HttpGet]
    public IActionResult Index()
    {
        var cuentas = _cuentaRepositorio.ObtenerTodos();
        ViewBag.Total = cuentas.Any() ? cuentas.Sum(o => o.SaldoInicial) : 0; 
        return View(cuentas);
    }
    
    [HttpGet]
    public IActionResult Create()
    {
        ViewBag.TipoDeCuentas = _tipoCuentaRepositorio.ObtenerTodos();
        return View(new Cuenta());
    }

    [HttpPost]
    public IActionResult Create(Cuenta cuenta)
    {
       if (cuenta.TipoId > 5 || cuenta.TipoId < 1)
        {
            ModelState.AddModelError("TipoCuentaId", "Tipo de cuenta no exite");
        }
    
        if (!ModelState.IsValid)
        {
            ViewBag.TipoDeCuentas = _tipoCuentaRepositorio.ObtenerTodos();
            return View("Create", cuenta);
        }

        //primero llamas al objeto y luego al metodo
        _cuentaRepositorio.GuardarCuenta(cuenta);
        return RedirectToAction("Index");

    }
    
    [HttpGet]
    public IActionResult Edit(int id)
    {
        //var cuenta = _dbEntities.Cuentas.First(o => o.Id == id); // lambdas / LINQ
        var cuenta = _cuentaRepositorio.ObtenerCuentaPorId(id);
        //ViewBag.TipoDeCuentas = _dbEntities.TipoCuentas.ToList();
        ViewBag.TipoDeCuentas = _tipoCuentaRepositorio.ObtenerTodos();
        return View(cuenta);
    }
    
    [HttpPost]
    public IActionResult Edit(int id, Cuenta cuenta)
    {
        if (!ModelState.IsValid) {
            ViewBag.TipoDeCuentas = _dbEntities.TipoCuentas.ToList();
            return View("Edit", cuenta);
        }
        
        //var cuentaDb = _dbEntities.Cuentas.First(o => o.Id == id);
        //var cuentaDb = _cuentaRepositorio.EditarCuentaPorId(id, cuenta);
        //cuentaDb.Nombre = cuenta.Nombre;
        //_dbEntities.SaveChanges();

       _cuentaRepositorio.EditarCuentaPorId(id, cuenta);
        
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public IActionResult Delete(int id)
    {
        //var cuentaDb = _dbEntities.Cuentas.First(o => o.Id == id);
        //var cuentaDb = _cuentaRepositorio.DeleteCuenta(id);
        //cuentaDb.Id = id;
        //_dbEntities.Cuentas.Remove(cuentaDb);
        //_dbEntities.SaveChanges();
        
        _cuentaRepositorio.DeleteCuenta(id);
        return RedirectToAction("Index");
        
    }

}

FinanzasWeb/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FinanzasWeb.Models;

namespace FinanzasWeb.Controllers;

public class HomeController : Controller
{
    // private readonly ILogger<HomeController> _logger;
    //
    // public HomeController(ILogger<HomeController> logger)
    // {
    //     _logger = logger;
    // }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

FinanzasWeb/Controllers/TransaccionController.cs
using FinanzasWeb.DB;
using FinanzasWeb.Models;
using FinanzasWeb.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace FinanzasWeb.Controllers;

public class TransaccionController : Controller
{
    private readonly ICuentaTransaccionRepositorio _cuentaTransaccionRepositorio;
    private DbEntities _dbEntities;
    
    
    public TransaccionController(ICuentaTransaccionRepositorio cuentaTransaccionRepositorio,
        DbEntities dbEntities)
    {
        _cuentaTransaccionRepositorio = cuentaTransaccionRepositorio;
        _dbEntities = dbEntities;
    
    }
    
    
    [HttpGet]
    public IActionResult Index(int cuentaId)
    {
        
        var items = _cuentaTransaccionRepositorio.ListaCuentaTransacciones(cuentaId);
        ViewBag.CuentaId = cuentaId;
        ViewBag.Total = items.Any() ? items.Sum(x => x.Monto) : 0;

        return View(items);
    }
    
    [HttpGet]
    public IActionResult Create(int cuentaId)
    {
        ViewBag.CuentaId = cuentaId;
        return View(new Transaccion());
    }
    
    [HttpPost]
    public IActionResult Create(int cuentaId, Transaccion transaccion)
    {
        if (transaccion.Monto == 0m)
        {
            ModelState.AddModelError("Monto: ", "El monto no puede ser 0");
        }
        
        if (!ModelState.IsValid)
        {
            ViewBag.CuentaId = cuentaId;
            return View(transaccion);
        }

        transaccion.Id = GetNextId();
        transaccion.CuentaId = cuentaId;
        if (transaccion.Tipo == "GASTO")
            transaccion.Monto *= -1;

        
        DbEntities.Transacciones.Add(transaccion);

        return RedirectToAction("Index", new { cuentaId = cuentaId});
    }
    
    public int GetNextId()  {
        if (DbEntities.Transacciones.Count == 0)
            return 1;
        return DbEntities.Transacciones.Max(o => o.Id) + 1;
    }
}

FinanzasWeb/Views/Cuenta/Create.cshtml
@using Microsoft.AspNetCore.Components.Forms

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 id="NuevaCuenta">Nueva Cuenta</h1>
            <form action="/cuenta/create" method="post">
                
                <div class="mb-3">
                    <label for="Nombre">Nombre</label>
                    <input type="text" class="form-control" Name="Nombre" id="Nombre" value="@Model.Nombre">
                    @Html.ValidationMessage("Nombre")
                </div>
                <div>
                    <label for="Categoria">Categoria</label>
                    <select class="form-select" name="Categoria" id="Categoria">
                        <option value="">-- Seleccione una categoria --</option>
                        <option value="PROPIO">Propio</option>
                        <option value="CREDITO">Credito</option>
                    </select>
                </div>
                
                <div class="mb-3">
                    <label for="TipoId">Tipo Cuenta</label>
                    
                    <select class="form-select" name="TipoId" id="TipoId">
                        <option value="">-- Seleccione un tipo de cuenta --</option>
                        @foreach (var item in ViewBag.TipoDeCuentas)
                        {
                            if (item.Id == Model.TipoId)
                            {
                                <option value="@item.Id" selected>@item.Nombre</option>
                            }
                            else
                            {
                                <option value="@item.Id">@item.Nombre</option>
                            }
                        }
                    </select>
                    
                    @Html.ValidationMessage("TipoCuentaId")
                </div>
                
                <div class="mb-3">
                    <label for="SaldoInicial">Saldo Inicial</label>
                    <input type="text" class="form-control" Name="SaldoInicial" id="SaldoInicial" value="@Model.SaldoInicial">
                    @Html.ValidationMessage("SaldoInicial")
                </div>
                <div>
                    <label for="Moneda">Moneda</label>
                    <select class="form-select" name="Moneda" id="Moneda">
                        <option value="">-- Seleccione la moneda --</option>
                        <option value="SOLES">Soles</option>
                        <option value="DOLARES">Dolares</option>
                    </select>
                </div>
                
                <br>
                <button class="btn btn-primary">Guardar</button>
                <a href="/cuenta/index" class="btn btn-danger">Cancelar</a>
            </form>
        </div>
    </div>

</div>

FinanzasWeb/Views/Cuenta/Edit.cshtml
@using Microsoft.AspNetCore.Components.Forms

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 id="NuevaCuenta">Nueva Cuenta</h1>
            <form action="/cuenta/create" method="post">
                
                <div class="mb-3">
                    <label for="Nombre">Nombre</label>
                    <input type="text" class="form-control" Name="Nombre" id="Nombre" value="@Model.Nombre">
                    @Html.ValidationMessage("Nombre")
                </div>
                <div>
                    <label for="Categoria">Categoria</label>
                    <select class="form-select" name="Categoria" id="Categoria">
                        <option value="PROPIO">Propio</option>
                        <option value="CREDITO">Credito</option>
                    </select>
                </div>
                
                <div class="mb-3">
                    <label for="TipoCuentaId">Tipo Cuenta</label>
                    
                    <select class="form-select" name="TipoCuentaId" id="TipoCuentaId">
                        <option value="">-- Seleccione un tipo de cuenta --</option>
                        @foreach (var item in ViewBag.TipoDeCuentas)
                        {
                            if (item.Id == Model.TipoCuentaId)
                            {
                                <option value="@item.Id" selected>@item.Nombre</option>
                            }
                            else
                            {
                                <option value="@item.Id">@item.Nombre</option>
                            }
                        }
                    </select>
                    
                    @Html.ValidationMessage("TipoCuentaId")
                </div>
                
                <div class="mb-3">
                    <label for="Monto">Monto</label>
                    <input type="text" class="form-control" Name="Monto" id="Monto" value="@Model.Monto">
                    @Html.ValidationMessage("Monto")
                </div>
                <div>
                    <label for="Moneda">Moneda</label>
                    <select class="form-select" name="Moneda" id="Moneda">
                        <option value="SOLES">Soles</option>
                        <option value="DOLARES">Dolares</option>
                    </select>
                </div>
                
                <br>
                <button class="btn btn-primary">Guardar</button>
                <a href="/cuenta/index" class="btn btn-danger">Cancelar</a>
            </form>
        </div>
    </div>

</div>

FinanzasWeb/Views/Cuenta/Index.cshtml
<div class="container">
    <h1 id="CuentaFinal">Cuentas</h1>
    <br>
    <a class="btn btn-primary" href="/cuenta/create">Nueva Cuenta</a>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Categoria</th>
             <td>Tipo de cuenta</td>
            <th>Salda Inicial</th>
            <th>Moneda</th>
            <td></td>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Nombre</td>
                <td>@item.Categoria</td>
                <td>@item.TipoCuenta.Nombre</td>
                <td>@item.SaldoInicial</td>
                <td>@item.Moneda</td>
                
                
                <td>
                    <a href="/Transaccion?cuentaId=@item.Id" class="btn btn-outline-success">Transacciones</a>
                    <a href="/cuenta/edit?id=@item.Id" class="btn btn-warning">Editar</a>
                    <a href="/cuenta/delete?id=@item.Id" class="btn btn btn-danger">Eliminar</a>
                </td>
            </tr>
        }
        </tbody>
    </table>

    Total Disponible real: @ViewBag.Total
</div>

FinanzasWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FinanzasWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - FinanzasWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/FinanzasWeb.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinanzasWeb</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Index">Finanzas</a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - FinanzasWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FinanzasWeb/Views/Transaccion/Create.cshtml
@using Microsoft.AspNetCore.Components.Forms

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1>Transacciones</h1>
            <form action="/Transaccion/create?cuentaId=@ViewBag.CuentaId" method="post">
                <div>
                    <label for="Tipo">Tipo</label>
                    <select class="form-select" name="Tipo" id="Tipo">
                        <option value="">-- Seleccione tipo --</option>
                        <option value="INGRESO">Ingreso</option>
                        <option value="GASTO">Gasto</option>
                    </select>
                </div>
                
               <div class="mb-3">
                    <label for="Fecha">Fecha</label>
                    <input type="datetime-local" class="form-control" Name="Fecha" id="Fecha" value="@Model.Fecha">
                    @Html.ValidationMessage("Fecha")
                </div>
                
                <div class="mb-3">
                    <label for="Descripcion">Descripcion</label>
                    <input type="text" class="form-control" Name="Descripcion" id="Descripcion" value="@Model.Descripcion">
                    @Html.ValidationMessage("Descripcion")
                </div>
                

                <div class="mb-3">
                    <label for="Monto">Monto</label>
                    <input type="text" class="form-control" Name="Monto" id="Monto" value="@Model.Monto">
                    @Html.ValidationMessage("Monto", new {id="MontoValidacion"})
                </div>
                
               
                <br>
                <button class="btn btn-primary">Guardar</button>
                <a href="/cuenta/index" class="btn btn-danger">Cancelar</a>
            </form>
        </div>
    </div>

</div>

FinanzasWeb/Views/Transaccion/Index.cshtml
<h1 id="TituloTransaccion">Transacciones</h1>

<a class="btn btn-primary" href="/Transaccion/create?cuentaId=@ViewBag.CuentaId">Nueva Transacción</a>

<table class="table">
    <thead>
    <tr>
        <td>Tipo</td>
        <th>Fecha</th>
        <th>Descripcion</th>
        <th>Monto</th>
        
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Tipo</td>
            <td>@item.Fecha</td>
            <td>@item.Descripcion</td>
            <td>@item.Monto</td>
            
            <td>
                <a href="/Transaccion/delete?id=@item.Id" class="btn btn btn-danger">Eliminar</a>
                
            </td>
        </tr>
    }    
    </tbody>
    
    <h1>Total: @ViewBag.Total</h1>
    
</table>